#!/usr/bin/env bash
set -euo pipefail

# Please ensure you have an active internet connection and sufficient permissions to install software on the new machine.
# Use the following command to run this script from a remote location (without downloading it first) in order to bootstrap the MacOS installation process:
# bash <(curl -fsSL https://raw.githubusercontent.com/dejannov/macos-setup-bootstrap/main/bootstrap)

SETUP_DIR="$HOME/Documents/setup"

echo "Bootstrapping MacOS setup environment..."

bash <(curl -fsSL https://raw.githubusercontent.com/dejannov/macos-setup-bootstrap/main/bootstrap-init)

if [[ ! -d "$SETUP_DIR/.git" ]]; then
  # Authenticate with GitHub
  if ! gh auth status >/dev/null 2>&1; then
    echo "Authenticate with GitHub..."
    gh auth login
  fi

  echo "Cloning private setup repository..."
  gh repo clone dejannov/macos-setup ~/Documents/setup
fi

echo "... MacOS setup environment is ready."

~/Documents/setup/run
