#!/usr/bin/env bash
set -euo pipefail

# Use the following command to run this script from a remote location (without downloading it first) in order to bootstrap the MacOS installation process:
# bash <(curl -fsSL https://raw.githubusercontent.com/dejannov/macos-setup/main/bootstrap)

echo "Bootstrapping MacOS environment..."
echo "This script will install Xcode Command Line Tools, Homebrew, GitHub CLI, and clone the private setup repository."
echo "You will be prompted to authenticate with GitHub during the process."
echo "Please ensure you have an active internet connection and sufficient permissions to install software on this machine."

if ! test -r "$HOME/Library/Application Support/com.apple.TCC/TCC.db"; then
    echo "Terminal needs Full Disk Access."
    echo
    echo "1. Open System Settings."
    echo "2. Privacy & Security → Full Disk Access."
    echo "3. Enable Terminal."
    echo "4. Quit Terminal completely."
    echo "5. Start Terminal again."
    echo "6. Re-run this script."
    exit 1
fi

# Install Git CLI if missing
firstTime=1
while ! xcode-select -p >/dev/null 2>&1; do
  if [[ $firstTime -eq 1 ]]; then
    echo "Installing Xcode Command Line Tools..."
    xcode-select --install || true
    firstTime=0
  fi

  echo "Please complete the installer window that has appeared (check the background for the installer)."
  sleep 5
done

echo "Installing Homebrew..."
if ! command -v brew >/dev/null 2>&1; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  if [[ -x /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
  elif [[ -x /usr/local/bin/brew ]]; then
    eval "$(/usr/local/bin/brew shellenv)"
  else
    echo "Homebrew installation failed."
    exit 1
  fi
fi

echo "Installing GitHub CLI..."
brew install gh

echo "Authenticate with GitHub..."
gh auth login

echo "Cloning private setup repository..."
gh repo clone dejannov/macos-setup ~/Documents/setup

~/Documents/setup/install
