#!/usr/bin/env bash
set -euo pipefail

echo "Bootstrapping MacOS environment..."

# Install Git CLI if missing
firstTime=1
while ! xcode-select -p >/dev/null 2>&1; do
  if [[ $firstTime -eq 1 ]]; then
    echo "Installing Xcode Command Line Tools..."
    xcode-select --install || true
    firstTime=0
  else
    echo "Please complete the installer window that has appeared (check the background for the installer)."
  fi

  sleep 5
done

echo "Installing Homebrew..."
if ! command -v brew >/dev/null 2>&1; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(brew shellenv)"
fi

echo "Installing GitHub CLI..."
brew install gh

echo "Authenticate with GitHub..."
gh auth login

echo "Cloning private setup repository..."
gh repo clone dejannov/macos-setup ~/Documents/setup

~/Documents/setup/install
